openapi: 3.0.0
info:
  title: Cat API
  description: API for managing cats
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /cats:
    get:
      summary: Get all cats
      responses:
        '200':
          description: A list of cats
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cat'
        '400':
          description: Bad Request
    post:
      summary: Add a new cat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cat'
      responses:
        '200':
          description: The added cat
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
        '400':
          description: Bad Request
  /cats/{id}:
    delete:
      summary: Remove a cat by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted the record
        '400':
          description: Bad Request
components:
  schemas:
    Cat:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        title:
          type: string
        position:
          type: string
        image:
          type: string
      required:
        - type
        - title
        - position
        - image
